[main]
file_path = "skate-3/default.xex"
# patch_file_path = ""
patched_file_path = "skate-3/default_patched.xex"
out_directory_path = "ppc"
switch_table_file_path = "skate-3/jump_table.toml"

# functions
restgprlr_14_address = 0x82f274e0
savegprlr_14_address = 0x82f27490
restfpr_14_address = 0x82f2845c
savefpr_14_address = 0x82f28410
restvmx_14_address = 0x82f2c4a8
savevmx_14_address = 0x82f2c210
restvmx_64_address = 0x82f2c53c
savevmx_64_address = 0x82f2c2a4

longjmp_address = 0x82f25260
setjmp_address = 0x82f44e40

invalid_instructions = [
    { data = 0x82052720, size = 0x0 },
    { data = 0x82052820, size = 0x0 },
    { data = 0x82052900, size = 0x0 },
    { data = 0x82052f70, size = 0x0 },
    { data = 0x8205f8c0, size = 0x0 },
    { data = 0x822f3240, size = 0x0 },
    { data = 0x822f3270, size = 0x0 },
    { data = 0x823c2564, size = 0x1b4 },
    { data = 0x823c94b4, size = 0x1b4 },
    { data = 0x823f0aac, size = 0xa0c },
    { data = 0x823f713c, size = 0x2c },
    { data = 0x823f785c, size = 0x1b8 },
    { data = 0x823fb1a8, size = 0x1b8 },
    { data = 0x823fd950, size = 0x154 },
    { data = 0x823ff330, size = 0x154 },
    { data = 0x82400618, size = 0x2c },
    { data = 0x824008b0, size = 0x2c },
    { data = 0x82400cb0, size = 0x2c },
    { data = 0x82400f78, size = 0x2c },
    { data = 0x82402618, size = 0x28 },
    { data = 0x824028b8, size = 0x28 },
    { data = 0x82403080, size = 0x2c },
    { data = 0x824220b4, size = 0x2c },
    { data = 0x824247b0, size = 0x50 },
    { data = 0x82457890, size = 0x34 },
    { data = 0x82457cf4, size = 0x34 },
    { data = 0x824583f4, size = 0x34 },
    { data = 0x8246479c, size = 0x34 },
    { data = 0x824791a0, size = 0x38 },
    { data = 0x82479428, size = 0x68 },
    { data = 0x82485784, size = 0x4c },
    { data = 0x82486f0c, size = 0x2c },
    { data = 0x82486fd4, size = 0x28 },
    { data = 0x82487440, size = 0x28 },
    { data = 0x8248c0ac, size = 0x38 },
    { data = 0x8248c530, size = 0x2c },
    { data = 0x82493210, size = 0x28 },
    { data = 0x82494408, size = 0x28 },
    { data = 0x82498d88, size = 0x34 },
    { data = 0x82498f34, size = 0xe8 },
    { data = 0x824995ac, size = 0x10c },
    { data = 0x82499c6c, size = 0x40 },
    { data = 0x82499d34, size = 0x44 },
    { data = 0x82499fe8, size = 0x34 },
    { data = 0x8249a8fc, size = 0x48 },
    { data = 0x824aabd0, size = 0x2c },
    { data = 0x824ccea8, size = 0x60 },
    { data = 0x824cef24, size = 0x2c },
    { data = 0x824cf388, size = 0x2c },
    { data = 0x824ea738, size = 0xcc },
    { data = 0x824efa94, size = 0x3c },
    { data = 0x824effe4, size = 0x138 },
    { data = 0x824f3318, size = 0x34 },
    { data = 0x824f33bc, size = 0x2c },
    { data = 0x824f4a80, size = 0x2c },
    { data = 0x824f564c, size = 0x30 },
    { data = 0x824f5784, size = 0x2c },
    { data = 0x824f5f28, size = 0x40 },
    { data = 0x824f8ed4, size = 0x104 },
    { data = 0x824f9c14, size = 0x34 },
    { data = 0x824f9ee0, size = 0x34 },
    { data = 0x824fb720, size = 0x38 },
    { data = 0x825091d0, size = 0x3c },
    { data = 0x8250a258, size = 0x3c },
    { data = 0x8250ebe8, size = 0x34 },
    { data = 0x8250f188, size = 0x30 },
    { data = 0x8250fdf4, size = 0x30 },
    { data = 0x8250fe7c, size = 0x34 },
    { data = 0x8250ff18, size = 0x2c },
    { data = 0x8250ff9c, size = 0x30 },
    { data = 0x82520c1c, size = 0x30 },
    { data = 0x82520cc0, size = 0x30 },
    { data = 0x825221b8, size = 0x34 },
    { data = 0x82523138, size = 0x34 },
    { data = 0x82527098, size = 0x34 },
    { data = 0x8252e1b8, size = 0x28 },
    { data = 0x8257dce0, size = 0x28 },
    { data = 0x8257f9a4, size = 0x34 },
    { data = 0x8258653c, size = 0x34 },
    { data = 0x825867a8, size = 0x38 },
    { data = 0x825869a4, size = 0x3c },
    { data = 0x82586c44, size = 0x40 },
    { data = 0x825b6758, size = 0x38 },
    { data = 0x825ba50c, size = 0x38 },
    { data = 0x825cb434, size = 0x28 },
    { data = 0x825cd64c, size = 0x44 },
    { data = 0x825d77f8, size = 0xbc },
    { data = 0x825d7a90, size = 0xc4 },
    { data = 0x825d9240, size = 0x38 },
    { data = 0x825d9d08, size = 0x40 },
    { data = 0x825e60e8, size = 0x3c },
    { data = 0x825f6fc8, size = 0x3c },
    { data = 0x825f7db8, size = 0x34 },
    { data = 0x825f800c, size = 0x40 },
    { data = 0x825f859c, size = 0x28 },
    { data = 0x825f892c, size = 0x38 },
    { data = 0x825f91ec, size = 0x50 },
    { data = 0x826002b0, size = 0x30 },
    { data = 0x8260059c, size = 0xb0 },
    { data = 0x826059ac, size = 0x28 },
    { data = 0x82606a14, size = 0x38 },
    { data = 0x82608b74, size = 0x44 },
    { data = 0x8260cd74, size = 0x4c },
    { data = 0x8261053c, size = 0x2c },
    { data = 0x82610aa8, size = 0x2c },
    { data = 0x82617a7c, size = 0x38 },
    { data = 0x82629d18, size = 0x64 },
    { data = 0x8262f76c, size = 0x5c },
    { data = 0x8263505c, size = 0x64 },
    { data = 0x82636ad0, size = 0x34 },
    { data = 0x82647688, size = 0x40 },
    { data = 0x8264fbc8, size = 0x38 },
    { data = 0x826567dc, size = 0x70 },
    { data = 0x826bc89c, size = 0x58 },
    { data = 0x826c3034, size = 0x34 },
    { data = 0x826c91dc, size = 0xb4 },
    { data = 0x826c9698, size = 0xcc },
    { data = 0x826cee24, size = 0x3c },
    { data = 0x826d98e0, size = 0x38 },
    { data = 0x826da138, size = 0xac },
    { data = 0x826e31b8, size = 0x7c },
    { data = 0x826e7350, size = 0x30 },
    { data = 0x826eaa64, size = 0x38 },
    { data = 0x826eac98, size = 0x34 },
    { data = 0x826eb3a0, size = 0x7c },
    { data = 0x826eb934, size = 0x64 },
    { data = 0x826edbd4, size = 0x84 },
    { data = 0x826efa2c, size = 0x30 },
    { data = 0x826f0404, size = 0x30 },
    { data = 0x826f1574, size = 0x30 },
    { data = 0x826f1f8c, size = 0x30 },
    { data = 0x826f2d38, size = 0x34 },
    { data = 0x826f5004, size = 0x28 },
    { data = 0x826f58ac, size = 0x28 },
    { data = 0x826f6884, size = 0x30 },
    { data = 0x82709d7c, size = 0x2c },
    { data = 0x8270d024, size = 0x4c },
    { data = 0x8270d52c, size = 0x4c },
    { data = 0x8270f48c, size = 0x30 },
    { data = 0x8270f82c, size = 0x38 },
    { data = 0x82718d2c, size = 0xc0 },
    { data = 0x8272944c, size = 0xd8 },
    { data = 0x82737c6c, size = 0x3c },
    { data = 0x8276013c, size = 0x68 },
    { data = 0x8277b8c8, size = 0x98 },
    { data = 0x8277bd48, size = 0x98 },
    { data = 0x82786fd0, size = 0x28 },
    { data = 0x827a68ec, size = 0x40 },
    { data = 0x827b70c4, size = 0x30 },
    { data = 0x827b8090, size = 0x28 },
    { data = 0x827fee20, size = 0x38 },
    { data = 0x82835d58, size = 0x8c },
    { data = 0x82836298, size = 0x8c },
    { data = 0x8288e0f4, size = 0x50 },
    { data = 0x8288e3ac, size = 0x48 },
    { data = 0x828928dc, size = 0x40 },
    { data = 0x828a9344, size = 0x30 },
    { data = 0x828aaaa0, size = 0x40 },
    { data = 0x828af3f0, size = 0x2c },
    { data = 0x828d0eec, size = 0x54 },
    { data = 0x828d1c00, size = 0x54 },
    { data = 0x828d1c7c, size = 0x2c },
    { data = 0x828d1e78, size = 0x2c },
    { data = 0x828d20b4, size = 0x2c },
    { data = 0x828d220c, size = 0x3c },
    { data = 0x828d2614, size = 0x3c },
    { data = 0x828d26e4, size = 0x3c },
    { data = 0x828d2864, size = 0x2c },
    { data = 0x828d2aa0, size = 0x64 },
    { data = 0x828d2d70, size = 0x38 },
    { data = 0x828d2f34, size = 0x5c },
    { data = 0x828d33dc, size = 0x5c },
    { data = 0x828d36a8, size = 0x64 },
    { data = 0x828d3940, size = 0x4c },
    { data = 0x828d5e6c, size = 0x58 },
    { data = 0x828d6170, size = 0x58 },
    { data = 0x828ede3c, size = 0x90 },
    { data = 0x828ee1f8, size = 0x30 },
    { data = 0x828f2724, size = 0x98 },
    { data = 0x828f87c8, size = 0x68 },
    { data = 0x828f8894, size = 0x6c },
    { data = 0x828f8abc, size = 0x3c },
    { data = 0x828f9f6c, size = 0x50 },
    { data = 0x828fc38c, size = 0x30 },
    { data = 0x828fcdb0, size = 0x28 },
    { data = 0x828fce98, size = 0x30 },
    { data = 0x828fd3d8, size = 0x3c },
    { data = 0x82923874, size = 0x3c },
    { data = 0x82923b18, size = 0x3c },
    { data = 0x82927f58, size = 0x3c },
    { data = 0x82928190, size = 0x3c },
    { data = 0x829286d4, size = 0x40 },
    { data = 0x8292895c, size = 0x40 },
    { data = 0x82928c88, size = 0x3c },
    { data = 0x82928f3c, size = 0x3c },
    { data = 0x82928fc0, size = 0x3c },
    { data = 0x82929218, size = 0x40 },
    { data = 0x82929404, size = 0x3c },
    { data = 0x8292a290, size = 0x3c },
    { data = 0x8292a8f8, size = 0x40 },
    { data = 0x8292ab7c, size = 0x40 },
    { data = 0x8292b360, size = 0x40 },
    { data = 0x8292b44c, size = 0x40 },
    { data = 0x8292c020, size = 0x48 },
    { data = 0x8292cd78, size = 0x70 },
    { data = 0x8292d350, size = 0x60 },
    { data = 0x82932e20, size = 0x28 },
    { data = 0x8293311c, size = 0x28 },
    { data = 0x829333a4, size = 0x28 },
    { data = 0x8293fa64, size = 0x74 },
    { data = 0x829421e8, size = 0x94 },
    { data = 0x82942d04, size = 0x28 },
    { data = 0x82943094, size = 0x84 },
    { data = 0x82944be4, size = 0x84 },
    { data = 0x829502c4, size = 0xdc },
    { data = 0x82959608, size = 0x2c },
    { data = 0x829596a8, size = 0x38 },
    { data = 0x82959774, size = 0x28 },
    { data = 0x8296dc5c, size = 0x2c },
    { data = 0x8296e0cc, size = 0x40 },
    { data = 0x8296e9d8, size = 0x30 },
    { data = 0x8297a80c, size = 0x30 },
    { data = 0x829a44d4, size = 0x3c },
    { data = 0x829a45f4, size = 0x54 },
    { data = 0x829a47a8, size = 0x28 },
    { data = 0x829a48c0, size = 0x2c },
    { data = 0x829a4a00, size = 0x28 },
    { data = 0x829a4b18, size = 0x48 },
    { data = 0x829a4bd4, size = 0x58 },
    { data = 0x829a4e08, size = 0x4c },
    { data = 0x829a4eb4, size = 0x50 },
    { data = 0x829a5000, size = 0x34 },
    { data = 0x829a51c4, size = 0x4c },
    { data = 0x829a536c, size = 0x34 },
    { data = 0x829a5420, size = 0x4c },
    { data = 0x829a54cc, size = 0x54 },
    { data = 0x829a5764, size = 0x54 },
    { data = 0x829a6ed0, size = 0x6c },
    { data = 0x829a73c0, size = 0x6c },
    { data = 0x829a767c, size = 0x6c },
    { data = 0x829a788c, size = 0x6c },
    { data = 0x829a79f0, size = 0xcc },
    { data = 0x829a8358, size = 0x25c },
    { data = 0x829a89d0, size = 0x1d0 },
    { data = 0x829a8db8, size = 0x3c },
    { data = 0x829a8fe8, size = 0x28 },
    { data = 0x829a9184, size = 0x3c },
    { data = 0x829a92b0, size = 0x30 },
    { data = 0x829a94a0, size = 0x4c },
    { data = 0x829a971c, size = 0x5c },
    { data = 0x829a98ac, size = 0x38 },
    { data = 0x829a9a10, size = 0x64 },
    { data = 0x829a9bec, size = 0x48 },
    { data = 0x829a9cd8, size = 0x30 },
    { data = 0x829aa038, size = 0x94 },
    { data = 0x829aa1b0, size = 0x58 },
    { data = 0x82a1d314, size = 0x28 },
    { data = 0x82a1d3bc, size = 0x28 },
    { data = 0x82a1d49c, size = 0x28 },
    { data = 0x82a29560, size = 0x28 },
    { data = 0x82a29630, size = 0x28 },
    { data = 0x82a29700, size = 0x28 },
    { data = 0x82a29980, size = 0x3c },
    { data = 0x82a29fdc, size = 0x40 },
    { data = 0x82a2a53c, size = 0x40 },
    { data = 0x82a30ae0, size = 0x28 },
    { data = 0x82a312b0, size = 0x28 },
    { data = 0x82a34fa4, size = 0x38 },
    { data = 0x82a50c18, size = 0x48 },
    { data = 0x82a54034, size = 0x50 },
    { data = 0x82a5500c, size = 0x34 },
    { data = 0x82a55588, size = 0x34 },
    { data = 0x82a5d490, size = 0x3c },
    { data = 0x82a702a0, size = 0x2c },
    { data = 0x82a8026c, size = 0x2c },
    { data = 0x82a84050, size = 0x2c },
    { data = 0x82ac1bd0, size = 0x44 },
    { data = 0x82ac2ac4, size = 0x48 },
    { data = 0x82ac3278, size = 0x48 },
    { data = 0x82ac40a8, size = 0x44 },
    { data = 0x82ac4b3c, size = 0x48 },
    { data = 0x82ae45c8, size = 0x30 },
    { data = 0x82ae70c4, size = 0x44 },
    { data = 0x82ae7498, size = 0xe0 },
    { data = 0x82ae82ec, size = 0x54 },
    { data = 0x82ae898c, size = 0x44 },
    { data = 0x82ae8d5c, size = 0xe0 },
    { data = 0x82ae9cb8, size = 0x54 },
    { data = 0x82aeb0e8, size = 0x38 },
    { data = 0x82aeb1a8, size = 0x2c },
    { data = 0x82b3a338, size = 0x1a0 },
    { data = 0x82b3ab1c, size = 0xc0 },
    { data = 0x82b3ee84, size = 0x1a0 },
    { data = 0x82b3f990, size = 0xc0 },
    { data = 0x82b4b558, size = 0x5c },
    { data = 0x82b6a554, size = 0x2c },
    { data = 0x82c00954, size = 0x4c },
    { data = 0x82c4cc00, size = 0x40 },
    { data = 0x82c50364, size = 0x30 },
    { data = 0x82c56104, size = 0x2c },
    { data = 0x82c596ec, size = 0x58 },
    { data = 0x82c59990, size = 0x58 },
    { data = 0x82c6ac14, size = 0x3c },
    { data = 0x82c71d38, size = 0x28 },
    { data = 0x82ce412c, size = 0xd4 },
    { data = 0x82cf0514, size = 0x2c },
    { data = 0x82cf0748, size = 0x28 },
    { data = 0x82d00af8, size = 0x44 },
    { data = 0x82d14e68, size = 0x30 },
    { data = 0x82d282d8, size = 0x28 },
    { data = 0x82d28364, size = 0x34 },
    { data = 0x82d70778, size = 0x38 },
    { data = 0x82d83424, size = 0x64 },
    { data = 0x82d897d8, size = 0x34 },
    { data = 0x82d9f0e4, size = 0x30 },
    { data = 0x82da026c, size = 0xc4 },
    { data = 0x82da0444, size = 0x30 },
    { data = 0x82da58fc, size = 0x5c },
    { data = 0x82da672c, size = 0x8c },
    { data = 0x82daa3d4, size = 0x30 },
    { data = 0x82ddc9e0, size = 0x60 },
    { data = 0x82e1f5e8, size = 0x48 },
    { data = 0x82e20c2c, size = 0x1b0 },
    { data = 0x82e22bb4, size = 0x54 },
    { data = 0x82e24e1c, size = 0x44 },
    { data = 0x82e2519c, size = 0x44 },
    { data = 0x82e26064, size = 0x34 },
    { data = 0x82e2b5a4, size = 0x54 },
    { data = 0x82e2bb14, size = 0x218 },
    { data = 0x82e2d208, size = 0x50 },
    { data = 0x82e2d600, size = 0x7c },
    { data = 0x82e2e094, size = 0x44 },
    { data = 0x82e32cb4, size = 0x34 },
    { data = 0x82e33ac0, size = 0x9c },
    { data = 0x82e34578, size = 0x98 },
    { data = 0x82e36b40, size = 0xcc },
    { data = 0x82e37338, size = 0x98 },
    { data = 0x82e3c694, size = 0x10c },
    { data = 0x82e4a1d8, size = 0x28 },
    { data = 0x82e4a6f8, size = 0x28 },
    { data = 0x82e4dd6c, size = 0x30 },
    { data = 0x82e61b78, size = 0x68 },
    { data = 0x82e63788, size = 0xd0 },
    { data = 0x82e7e9b4, size = 0x44 },
    { data = 0x82e821c8, size = 0x38 },
    { data = 0x82e82b04, size = 0x28 },
    { data = 0x82e83e78, size = 0x28 },
    { data = 0x82e8aed8, size = 0x40 },
    { data = 0x82e8f8fc, size = 0x40 },
    { data = 0x82e9b8c4, size = 0x48 },
    { data = 0x82ea8158, size = 0x48 },
    { data = 0x82eda864, size = 0x28 },
    { data = 0x82ef799c, size = 0x2c },
    { data = 0x82ef7f6c, size = 0xd4 },
    { data = 0x82efe718, size = 0x3c }
]

functions = [
    { address = 0x82a1d278, size = 0x2D5 },
    { address = 0x8288df68, size = 0x534 }, # for some reason this one cant point to the instruction after the end
    { address = 0x8270f678, size = 0x290 },
    { address = 0x826ea9a0, size = 0x110 },
    { address = 0x826d9728, size = 0x210 },
    { address = 0x82486d00, size = 0x288 },
    { address = 0x824f9bc8, size = 0x398 },
    { address = 0x8257dae0, size = 0x480 },
    { address = 0x825d3a08, size = 0x1e0 },
    { address = 0x823f7108, size = 0x2d0 },
    { address = 0x823fb170, size = 0xb68 },
    { address = 0x824005e8, size = 0x488 },
    { address = 0x82400880, size = 0x1f0 },
    { address = 0x82400c80, size = 0x2c8 },
    { address = 0x82400f48, size = 0x298 },
    { address = 0x824025e8, size = 0x2a0 },
    { address = 0x82402888, size = 0x220 },
    { address = 0x82403050, size = 0x238 },
    { address = 0x82422068, size = 0xc8 },
    { address = 0x82424790, size = 0x1b8 },
    { address = 0x82485750, size = 0x148 },
    { address = 0x82486f88, size = 0x320 },
    { address = 0x82498ad8, size = 0x950 },
    { address = 0x82499c28, size = 0x2c0 },
    { address = 0x8249a730, size = 0x328 },
    { address = 0x824aab90, size = 0x1b8 },
    { address = 0x824cce68, size = 0xd8 },
    { address = 0x824ced08, size = 0x450 },
    { address = 0x824cf340, size = 0xe8 },
    { address = 0x824ea708, size = 0x310 },
    { address = 0x824efa58, size = 0x488 },
    { address = 0x82509198, size = 0x100 },
    { address = 0x8250a220, size = 0x100 },
    { address = 0x8250fdd0, size = 0x88 },
    { address = 0x8250fe58, size = 0x98 },
    { address = 0x8250fef0, size = 0x88 },
    { address = 0x8250ff78, size = 0x88 },
    { address = 0x825864c8, size = 0x298 },
    { address = 0x82586760, size = 0x1d0 },
    { address = 0x82586930, size = 0x2e0 },
    { address = 0x82586c10, size = 0x218 },
    { address = 0x825ba4c8, size = 0x258 },
    { address = 0x825cb3e8, size = 0x198 },
    { address = 0x825cd610, size = 0x330 },
    { address = 0x825d79f0, size = 0x240 },
    { address = 0x82600268, size = 0x160 },
    { address = 0x826058a8, size = 0x380 },
    { address = 0x82629cd8, size = 0x1f0 },
    { address = 0x82635010, size = 0x1d8 },
    { address = 0x82656788, size = 0x170 },
    { address = 0x826bc838, size = 0x4a8 },
    { address = 0x826c9198, size = 0x4a8 },
    { address = 0x826ef9f8, size = 0x210 },
    { address = 0x826f1538, size = 0x1f8 },
    { address = 0x826f1f48, size = 0x258 },
    { address = 0x826f4fc8, size = 0x1a0 },
    { address = 0x826f5870, size = 0x1d8 },
    { address = 0x82709d28, size = 0x210 },
    { address = 0x8270cff0, size = 0x170 },
    { address = 0x8270d4c8, size = 0x178 },
    { address = 0x8270f458, size = 0x1c8 },
    { address = 0x82718cf8, size = 0x660 },
    { address = 0x827293f8, size = 0x498 },
    { address = 0x82786f98, size = 0x100 },
    { address = 0x828f8798, size = 0x1a8 },
    { address = 0x828f9f28, size = 0x220 },
    { address = 0x828fcd68, size = 0xe8 },
    { address = 0x828fce50, size = 0x198 },
    { address = 0x82923820, size = 0x568 },
    { address = 0x8293fa18, size = 0x128 },
    { address = 0x829502a0, size = 0x480 },
    { address = 0x829595b8, size = 0x338 },
    { address = 0x8296e9b8, size = 0x150 },
    { address = 0x829a41c0, size = 0x2970 },
    { address = 0x829a6e88, size = 0x4e0 },
    { address = 0x829a7368, size = 0x2e0 },
    { address = 0x829a7648, size = 0x210 },
    { address = 0x829a7858, size = 0x2360 },
    { address = 0x829a9bb8, size = 0x8c8 },
    { address = 0x82a29450, size = 0x448 },
    { address = 0x82a29bb0, size = 0x560 },
    { address = 0x82a2a110, size = 0x560 },
    { address = 0x82a30ac0, size = 0x138 },
    { address = 0x82a31268, size = 0x150 },
    { address = 0x82a50bc0, size = 0x150 },
    { address = 0x82a53fd0, size = 0x1a0 },
    { address = 0x82a80228, size = 0x140 },
    { address = 0x82ac1b98, size = 0x98 },
    { address = 0x82abf47a, size = 0xc4 },
    { address = 0x82ac4070, size = 0x98 },
    { address = 0x82b3a2f8, size = 0x7d8 },
    { address = 0x82b3aad0, size = 0x4b8 },
    { address = 0x82b3ee40, size = 0xb08 },
    { address = 0x82b3f948, size = 0x6c0 },
    { address = 0x82b64db0, size = 0x4e8 },
    { address = 0x82c4cbc0, size = 0x110 },
    { address = 0x82ce40e8, size = 0xfd0 },
    { address = 0x82d14df8, size = 0x238 },
    { address = 0x82d282b0, size = 0x60 },
    { address = 0x82d83360, size = 0x2c0 },
    { address = 0x82ddc9a8, size = 0x500 },
    { address = 0x82e1f590, size = 0xc08 },
    { address = 0x82e22b70, size = 0x5b0 },
    { address = 0x82e24dc0, size = 0x378 },
    { address = 0x82e25138, size = 0x638 },
    { address = 0x82e32c58, size = 0x9a0 },
    { address = 0x82e33a40, size = 0x590 },
    { address = 0x82e344f0, size = 0x3d0 },
    { address = 0x82e37308, size = 0xd8 },
    { address = 0x82e4dd18, size = 0xd0 },
    { address = 0x82e61b30, size = 0x1c8 },
    { address = 0x82e8aeb8, size = 0xa8 },
    { address = 0x82e9b870, size = 0x278 },
    { address = 0x82f44908, size = 0x200 },
]